name: kebut_kurir
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  camera: ^0.10.5
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  dio: ^5.1.1
  fimber: ^0.6.6
  firebase_core: ^2.10.0
  firebase_dynamic_links: 5.3.3
  flutter:
    sdk: flutter
  flutter_callkit_incoming: ^2.0.0
  flutter_html: any
  flutter_image_compress: 2.0.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_native_image: ^0.0.6+1
  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.6.0
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.2
  flutter_typeahead: ^4.6.1
  fluttertoast: ^8.1.1
  freerasp: ^3.0.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  get_it: ^7.3.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.7
  google_mlkit_text_recognition:
    path: C:\Users\recov\Documents\Ozan\Repo
      Flutter\google_mlkit_text_recognition-0.11.0-custom
  http_parser: null
  image_picker: ^0.8.7+5
  injectable: ^2.1.1
  intl: any
  nfc_manager: ^3.2.0
  objectbox: ^1.7.0
  objectbox_flutter_libs: ^1.7.0
  open_mail_app: ^0.4.5
  package_info_plus: ^3.0.2
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  qr_code_scanner: ^1.0.1
  screenshot: ^2.1.0
  shared_preferences: ^2.1.1
  shimmer: ^2.0.0
  skeletons: ^0.0.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5

flutter:

  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  background_color: "#ffffff"
  image_path: "assets/icon_kebut.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/bg_splash.png
  color: "#FFFFE6"
