name: kebut_kurir
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  intl: any
  permission_handler: ^10.2.0
  flutter_phone_direct_caller: ^2.1.1
  get: ^4.6.5
  flutter_html: any
  flutter_typeahead: ^4.6.1
  google_ml_kit: ^0.14.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  freerasp: ^3.0.2
  url_launcher: ^6.1.7
  share_plus: ^7.0.1
  shared_preferences: ^2.1.1
  flutter_statusbarcolor_ns: ^0.5.0
  get_it: ^7.3.0
  callkeep: ^0.3.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  file_picker: ^5.3.1
  image_picker: ^0.8.7+5
  google_maps_flutter: ^2.2.7
  dio: ^5.1.1
  firebase_core: ^2.4.1
  google_sign_in: ^5.4.2
  pinput: ^2.2.31
  firebase_auth: ^4.2.4
  camera: ^0.10.5
  http_parser:
  firebase_dynamic_links: ^5.3.3
  fimber: ^0.6.6
  open_mail_app: ^0.4.5
  flutter_native_image: ^0.0.6+1
  flutter_image_compress: 2.0.3
  fluttertoast: ^8.1.1
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.4
  skeletons: ^0.0.3
  screenshot: ^2.1.0
  flutter_native_splash: ^2.2.19
  injectable: ^2.1.1
  flutter_screenutil: ^5.6.0
  objectbox: ^1.7.0
  flutter_callkit_incoming: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1
  nfc_manager: ^3.2.0
  package_info_plus: ^3.0.2
  objectbox_flutter_libs: ^1.7.0
  firebase_messaging: ^14.6.1
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  background_color: "#ffffff"
  image_path: "assets/icon_kebut.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: assets/splash.png
